version: '3'
services:
  porsche:
    build: .
    restart: always
    environment:
    - PORSCHE_USER=
    - PORSCHE_PASSWORD=
    - VIN=
    - INFLUX_URL=http://192.168.0.100:8086
    - INFLUX_BUCKET=cars
    - INFLUX_ORG=home
    - INFLUX_TOKEN=
    - INFLUX_MEASUREMENT=status
    #- INFLUX_MAP_FILE=/porsche/influx_map.json # If you want to overwrite it, you can provide your own by setting a location via a volume
    - INTERVAL=5000 # Get/Write values every X ms
    - INTERVAL_PARKED=60000 # Get/Write values every X ms when parked
  #volumes:
  #  - /home/home/porsche/influx_map.json:/porsche/influx_map.json
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"